export const DELETE_USER = "DELETE_USER"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const CHANGE_USER = "CHANGE_USER"
export const ADD_USER = "ADD_USER"
export const OPEN_MODAL = "OPEN_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"